### ISSUE TITLE
DBAPI unterschiedlich

### ISSUE THREAD

**Issue by dengelhardt011** [horchi/vdr-plugin-epg2vdr#4]
Hallo, 

ich wollte mir eine neue mariaDB aufbauen, weil ich meine alte DB dorthin umziehen möchte. Mein epg-daemon funktioniert mit der neuen DB, aber bei dem VDR-Plugin "epg2vdr" bekomme ich diese Fehlermeldung. Was mich ein bissi verwirrt, denn die alte DB läuft auf einer ubuntu22.04 Maschine und die neue ebenfalls. Die MariaDB Versionen sind für mich identisch.

Gib es Pläne den epg2vdr zu updaten? Oder soll ich die MariaDB version ändern ? 

`
Mar 14 09:55:00 vdbe-home vdr[770352]: epg2vdr: Trying to re-connect to database!
Mar 14 09:55:00 vdbe-home vdr[770352]: epg2vdr: Found dbapi 8, expected 7, please update me! Aborting now.
Mar 14 09:55:00 vdbe-home vdr[770352]: epg2vdr: Retry #2 failed, retrying in 10 seconds!
`

MariaDB Version alter Maschine ->

`
└─># mysql -uroot -p<Secret> -h<HOST> -e "SELECT @@version;"
+----------------------------------+
| @@version                        |
+----------------------------------+
| 10.6.16-MariaDB-0ubuntu0.22.04.1 |
+----------------------------------+
`

MariaDB Version neuer Maschine ->

`
└─># mysql -uroot -p<Secret> -h<HOST> -e "SELECT @@version;"
+----------------------------------+
| @@version                        |
+----------------------------------+
| 10.6.16-MariaDB-0ubuntu0.22.04.1 |
+----------------------------------+
`

**Comment by horchi** [comment]
diese Meldung hat nichts mir der Datenbank selbst zu tun sondern nur mit der Struktur der Tabellen welche vom epgd verwalte wird.
Das epg2vdr Plugin erwartet in deinem Fall eine ältere als der epgd bereitstellt. Also einfach das Plugin auf den selben Stand bringen ....

**Comment by dengelhardt011** [comment]
Alles klar dank dir für deine Antwort. Ich prüfe das mal ich dachte eigentlich, dass ich beides aktuell aus git gezogen haben und frisch kompiliert habe.
